name: Lint with ruff

on:
  push:
    branches:
      - main
      - dev

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: pip
      - run: ruff check --fix
      - run: ruff format
