name: Lint with ruff

on:
  push:
    branches:
      - main
      - dev

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  |
          curl -LsSf https://astral.sh/ruff/install.sh | sh
          source $HOME/.local/bin/env
          ruff check --fix
          ruff format
