name: unittests

on:
  push:
    branches:
      - main
      - dev
      - workflows

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu:noble
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: pip
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - run:  |
          pip install -r ./archebot/src/archebot/test/requirements.txt
          pytest
