name: unittests

on:
  push:
    branches:
      - main
      - dev
      - workflows
      - oa-tests

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: actions/checkout@v3

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic

      - name: Install dependencies and run tests
        shell: bash
        run: |
          apt update
          apt install -y python3-pip ros-noetic-sensor-msgs ros-noetic-roslaunch
          source /opt/ros/noetic/setup.bash
          
          echo "ROS_PACKAGE_PATH: $ROS_PACKAGE_PATH"
          python3 --version
          pip3 --version
          which python3
          which pip3
          
          pip3 install uv
          UV_SYSTEM_PYTHON=$(which python3) uv pip install -r requirements.txt --system
          pytest
